## Indexing and Slicing in NumPy array

Indexing

In [ ]:
import numpy as np
var = np.array([11,12,13,44,55,76,21])
print(var[5])

76


In [ ]:
import numpy as np
var = np.array([11,12,13,44,55,76,21])
print(var[5])
print(var[-3])

76
[12 13 44]
55


In [8]:
## two dimensional array

import numpy as np
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var[1][2])
print(var[0,3])



7
4


How to print in 3D array

In [12]:
var1 = np.array([[[1,2,3,4],[5,6,7,9]], [[6,3,1,4],[9,8,7,6]]])
print(var1[1][0][2])
print(var1[0,0,3])

1
4


In [13]:
var1 = np.array([[[1,2,3,4],[5,6,7,9]], [[6,3,1,4],[9,8,7,6]]])
print(var1[1][0][2])
print(var1[0,0,1:])

1
[2 3 4]


## Slicing

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
print(var[1:5])

[2 3 4 5]


In [ ]:
## print the number from given number to the ending number

import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
print(var[2:])

[3 4 5 6 7 8 9]


In [ ]:
## print the element from starting to the given number

import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
print(var[:4])

[1 2 3 4]


In [17]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
print(var[1:8:2])

[2 4 6 8]


In [19]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1[1][1:])

[8 7 6 5]
