## Iterating NumPy Array

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5 6]

1
2
3
4
5
6


In [ ]:
import numpy as np
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print()
for j in var:
    print(j)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]


In [3]:
import numpy as np
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print()
for j in var:
    print(j)

for k in var:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


In [6]:
var = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var)
print(var.ndim)
print()
for j in var:
    for k in j:
        print(k)

[[[1 2 3 4]
  [5 6 7 8]]]
3

[1 2 3 4]
[5 6 7 8]


In [7]:
var = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var)
print(var.ndim)
print()
for j in var:
    for k in j:
        for m in k:
            print(m)

[[[1 2 3 4]
  [5 6 7 8]]]
3

1
2
3
4
5
6
7
8


nditer() function :- in thse function we did not repeat for loop.

In [ ]:
var = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var)
print(var.ndim)
print()
for i in np.nditer(var):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
3

1
2
3
4
5
6
7
8


how to change datatype

flag[''buffered] = it create extra space

op_dtypes=['S'] - it give operation data type string(S)

In [15]:
var = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var)
print(var.ndim)
print()
for i in np.nditer(var, flags=['buffered'],op_dtypes=["S"]):
    print(i)


[[[1 2 3 4]
  [5 6 7 8]]]
3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')


ndenumerate() :- it give indexing value

In [16]:
var = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var)
print(var.ndim)
print()
for i,d in np.ndenumerate(var):
    print(i,d)


[[[1 2 3 4]
  [5 6 7 8]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
