# Joining and Split NumPy array using python

join array :- join array mean putting condtent of two or more array in single aray.

Join

In [ ]:
## conatenate method

import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

x = np.concatenate((var1,var2))
print(x)

[1 2 3 4 5 6 7 8]


In [13]:
## 2D array

var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[9,8,7,6],[4,3,2,1]])
print(var1)
print()
print(var2)
print()
x = np.concatenate((var1,var2), axis=0)
print(x)

[[1 2 3 4]
 [5 6 7 8]]

[[9 8 7 6]
 [4 3 2 1]]

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [4 3 2 1]]


stack() function

In [15]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

y = np.stack((var_1,var_2), axis=1)
print(y)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


hstack() :- merge the data along the row

In [ ]:
## work according to row
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

y = np.hstack((var_1,var_2))
print(y)

[1 2 3 4 5 6 7 8]


dstack() :- merge the data along to the height

In [ ]:
## work according to height
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

y = np.dstack((var_1,var_2))
print(y)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [20]:
## work according to column
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

y = np.vstack((var_1,var_2))
print(y)

[[1 2 3 4]
 [5 6 7 8]]


Split Array :- spliting break one array into multiple

In [24]:
import numpy as np
var = np.array([1,2,3,4,5,6])
x = np.array_split(var,3)
print(var)
print()
print(x)

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6])
x = np.array_split(var,4)
print(var)
print()
print(x)
print(type(x)) # type is list

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5]), array([6])]
<class 'list'>


In [30]:
import numpy as np
var = np.array([1,2,3,4,5,6])
x = np.array_split(var,4)
print(var)
print()
print(x)
print(x[1]) ## int

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[3 4]


In [37]:
#2D array

import numpy as np
var = np.array([[1,2,3],[5,6,7],[8,5,2]])
x = np.array_split(var,2)
print()
print(x)


[array([[1, 2, 3],
       [5, 6, 7]]), array([[8, 5, 2]])]


In [38]:
## axis = 1

#2D array

import numpy as np
var = np.array([[1,2,3],[5,6,7],[8,5,2]])
x = np.array_split(var,2,axis=1)
print()
print(x)


[array([[1, 2],
       [5, 6],
       [8, 5]]), array([[3],
       [7],
       [2]])]
