# What are NumPy array function

Search array :- Search array an array for a certain value, and return the indexes that gets a match

search

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5])
x = np.where(var == 3)
print(x)

(array([2]),)


In [ ]:
import numpy as np
var = np.array([1,2,3,2,4,5,2])
x = np.where(var == 2)
print(x)

(array([1, 3, 6]),)


In [6]:
## division
import numpy as np
var = np.array([2,3,4,5,6,7,8])
x = np.where((var%2==0))
print(x)


(array([0, 2, 4, 6]),)


Search Sorted Array :- which perform binary search in the array and return the indexes where the specified value would be inserted to maintain the search order

In [ ]:
## it show you where to insert the value.
var = np.array([1,2,3,4,6])
x = np.searchsorted(var, 5)
print(x)

4


In [17]:
## it show you where to insert the value.
var = np.array([1,2,3,4,6,7,8,9,2,3])
x = np.searchsorted(var, 5,side="right")
print(x)

4


sort() :- sorting the number.

In [21]:
var1 = np.array([9,3,4,6,1,5,2])

x = np.sort(var1)
print(x)

[1 2 3 4 5 6 9]


In [23]:
var1 = np.array(["a","s","d","v","b"])

print(np.sort(var1))

['a' 'b' 'd' 's' 'v']


In [26]:
var1 = np.array([[1,5,2],[3,7,6],[4,9,8]])

x = np.sort(var1)
print(x)

[[1 2 5]
 [3 6 7]
 [4 8 9]]


Filter array() :- getting some element out of an existing array and creating a new array out of them.

In [33]:
var1 = np.array(["a","s","d","f"])

x = [True,False,False,True]
new_a = var1[x]
print(new_a)

['a' 'f']
