## NumPy Arithmatic function

Shuffle

Unique

Resize

Flatten

Ravel

  Shuffle() :- it give different number every time number is not in sequence

In [6]:
import numpy as np
var1 = ([1,2,3,4,5])
np.random.shuffle(var1)
print(var1)

[2, 4, 5, 1, 3]


unique() :- it give only unique number 

In [ ]:
import numpy as np
var1 = ([1,2,3,2,4,5,3,2])
x=np.unique(var1)
print(x)

[1 2 3 4 5]


In [12]:
## return_index give the index number

import numpy as np
var1 = ([1,2,3,2,4,5,3,2,7])
x=np.unique(var1,return_index=True)
print(x)

(array([1, 2, 3, 4, 5, 7]), array([0, 1, 2, 4, 5, 8]))


In [16]:
## return_count (count the number how many time it repeat)

import numpy as np
var1 = ([1,2,3,2,4,5,3,2,7])
x=np.unique(var1,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 7]), array([1, 3, 2, 1, 1, 1]))


resize() :- you can resize it by the rows and column

In [18]:
## return_count (count the number how many time it repeat)

import numpy as np
var1 = ([1,2,3,4,5,6])
x=np.resize(var1,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


flatten() :- the flatten method convert two dimensional array to one dimensional array

In [25]:
## return_count (count the number how many time it repeat)

import numpy as np
var1 = ([[1,2,3],[4,5,6]])
y = np.resize(var1,(2,3))
print(y)
print(y.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [26]:
## order="F" to change the order

import numpy as np
var1 = ([[1,2,3],[4,5,6]])
y = np.resize(var1,(2,3))
print(y)
print(y.flatten(order="F"))

[[1 2 3]
 [4 5 6]]
[1 4 2 5 3 6]


 ravel() method give you the original value

In [ ]:

## order="F" to change the order

import numpy as np
var1 = ([[1,2,3],[4,5,6]])
y = np.resize(var1,(2,3))
print(y)
print(y.flatten(order="F"))
print(np.ravel(y))

[[1 2 3]
 [4 5 6]]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
