## Insert and Delete in NumPy array

insert() :- insert method into an element

In [11]:
import numpy as np
var = np.array([1,2,3,4,5])

print(var)

x = np.insert(var,2,44)
print(x)

[1 2 3 4 5]
[ 1  2 44  3  4  5]


In [14]:
import numpy as np
var = np.array([1,2,3,4,5])

print(var)

x = np.insert(var,(2, 4), 44)
print(x)

[1 2 3 4 5]
[ 1  2 44  3  4 44  5]


In [21]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])

print(var)

x = np.insert(var,2,6,axis=0)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [6 6 6]]


In [22]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])

print(var)

x = np.insert(var,2,6,axis=1)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 6 3]
 [4 5 6 6]]


In [24]:
## how to give a multiple data

import numpy as np
var = np.array([[1,2,3],[4,5,6]])

print(var)

x = np.insert(var,2,[9,8],axis=1)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 9 3]
 [4 5 8 6]]


In [26]:
## how to give a multiple data

import numpy as np
var = np.array([[1,2,3],[4,5,6]])

print(var)

x = np.insert(var,2,[9,8,1],axis=0)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [9 8 1]]


append() :- append method add element into the last

In [27]:
import numpy as np
var = np.array([1,2,3,4,5])

print(var)

x = np.append(var, 88)
print(x)

[1 2 3 4 5]
[ 1  2  3  4  5 88]


In [29]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])

print(var)

x = np.append(var, [[7,8,9]],axis=0)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


delete() :- how to delete the data

In [34]:
import numpy as np
var = np.array([1,2,3,4,5])

print(var)

x = np.delete(var,3)
print(x)

[1 2 3 4 5]
[1 2 3 5]
