## Concept of matrix in NumPy array

Matrix

In [8]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)


[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
x = np.matrix(var)
print(var)
print(type(x))


[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


Addition in matrix

In [9]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
var1 = np.array([[1,2,3],[4,5,6]])
print(var+var1)


[[ 2  4  6]
 [ 8 10 12]]


miltiplication

In [14]:
import numpy as np
var = np.matrix([[1,2],[4,5]])
var1 = np.matrix([[1,2],[4,5]])
print(var.dot(var1))


[[ 9 12]
 [24 33]]


In [15]:
import numpy as np
var = np.matrix([[1,2],[4,5]])
var1 = np.matrix([[1,2],[4,5]])
print(var*var1)


[[ 9 12]
 [24 33]]


Matrix Function

Transpose

Swapaxes

Inverse

Power

Determinate

transpose

In [27]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print("Transpose")
var = np.transpose([[1,2,3],[4,5,6]])
print(var)

[[1 2 3]
 [4 5 6]]

Transpose
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
## shortest method to transpose matrix using capital T method
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var.T)


[[1 4]
 [2 5]
 [3 6]]


swapaxes

In [34]:
## it concert 0(column) axis into 1(row) axis
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
print(var)
print()
x = np.swapaxes(var,0,1)
print(x)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


Inverse matrix

In [ ]:
## it inverse the matrix
import numpy as np
var = np.array([[1,2],[4,5]])
print(var)
print()
x = np.linalg.inv(var)
print(x)


[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


Power

In [47]:
import numpy as np
var = np.array([[1,2],[4,5]])
x = (np.linalg.matrix_power(var,2))
print(x)

[[ 9 12]
 [24 33]]


In [48]:
import numpy as np
var = np.array([[1,2],[4,5]])
x = (np.linalg.matrix_power(var,2))
print(x)
x = (np.linalg.matrix_power(var,0))
print(x)

[[ 9 12]
 [24 33]]
[[1 0]
 [0 1]]


A = a b c

     d e f    |a| = a[ei - hf] -b[di - gf] +c[dh - eg]

     g h i

np.linalg.det(var)

In [49]:
import numpy as np
var = np.array([[1,2],[3,4]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [3 4]]

-2.0000000000000004


In [50]:
import numpy as np
var = np.array([[1,2,3],[3,4,3],[1,2,3]])
print(var)
print()
print(np.linalg.det(var))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
