## How to create NumPy array using NumPy function

Spatial NumPy array

1. Array filled with 0's.

2. Array filled with 1'.

3. An array with a range of element.

4. Array diagonal element filled with 1's.

5. Create an array with values that are space linearly in a specified interval



Array filled with zero

In [ ]:
## one dimension array
import numpy as np

arr_0 = np.zeros(4)
print(arr_0)

[0. 0. 0. 0.]


In [ ]:
## two dimension array fill zero's
import numpy as np

arr_0 = np.zeros((4,4))
print(arr_0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array filled with 1's

In [9]:
## two dimension array
import numpy as np

arr_0 = np.ones((4,4))
print(arr_0)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Empty array

In [10]:
n = np.empty(4)
print(n)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323]


arange() :  Array with a range of element

In [11]:
## two dimension array
import numpy as np

arrg= np.arange((7))
print(arrg)

[0 1 2 3 4 5 6]


Diagonal

In [12]:
## two dimension array
import numpy as np

dgn = np.eye(4)
print(dgn)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
## two dimension array
import numpy as np

dgn = np.eye(4,4)
print(dgn)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create an array with values that are space linearly in a specified interval

linspace

In [15]:
lin = np.linspace(0, 10, num=5)
print(lin)
print(type(lin))

[ 0.   2.5  5.   7.5 10. ]
<class 'numpy.ndarray'>
