## How to create NumPy array with random number

1. rand() :- the function is used to generate a random value between 0 to 1

2. randn() :- the function is used to generate a random value closed to zero. This may return positive or negative number as well.

3. ranf() :- th function for doing random sampling in numpy. It return an array of specified shape and fill it with random float in the half open interval [0.0, 1.0]

4. randint() :- the function is used to generate number between a given range.

rand()

In [2]:
## 1-D array it give random number everytime
import numpy as np

ran = np.random.rand(4)
print(ran)

[0.94223825 0.13601333 0.74806451 0.39909893]


In [4]:
## 2-D array it give random number everytime
import numpy as np

ran = np.random.rand(3,5)
print(ran)

[[0.58841295 0.9896681  0.86347077 0.00647551 0.33580831]
 [0.10558713 0.99036945 0.34713489 0.42536355 0.50777798]
 [0.62788942 0.97206869 0.02415441 0.38368302 0.62590577]]


randn()

In [3]:
## 1-D array it give random number everytime
import numpy as np

ran = np.random.randn(4)
print(ran)

[-1.29315645  1.23346959  0.66101091 -1.00750071]


ranf()

In [6]:
## 1-D array it give random number everytime
import numpy as np

ran = np.random.ranf(4)
print(ran)

[0.98142533 0.92697415 0.68747053 0.90821681]


randint()

In [14]:
## It generate a random number betwee max,min,total_value
import numpy as np

##ran = np.random.randint(min,max,total_value)
ran = np.random.randint(4,20,5)
print(ran)

[14 17 12 18 13]
