Data Type

In [2]:
import numpy as np

var = np.array([1, 2, 3, 4, 5])
print(var)
print("Data Type : ", var.dtype)

[1 2 3 4 5]
Data Type :  int64


In [3]:
import numpy as np

var = np.array([1.1, 2.4, 5, 6]) ## floating data type
print(var)
print("Data Type : ", var.dtype)

[1.1 2.4 5.  6. ]
Data Type :  float64


In [ ]:
import numpy as np

var = np.array(['a', 'b', 'c', 'd'])  ## string data type
print(var)
print("Data Type : ", var.dtype)

['a' 'b' 'c' 'd']
Data Type :  <U1


In [7]:
import numpy as np

v = np.array(['a', 'b', 'c', 'd', 1, 2, 3, 4])  ## string and int data type
print(v)
print("Data Type : ", v.dtype)

['a' 'b' 'c' 'd' '1' '2' '3' '4']
Data Type :  <U21


Convert the data type int32 to int8

In [10]:
import numpy as np

var = np.array([1, 2, 3, 4, 5])
print(var)
print("Data Type : ", var.dtype)

print()

var = np.array([1, 2, 3, 4, 5], dtype= np.int8)
print(var)
print("Data Type : ", var.dtype)

[1 2 3 4 5]
Data Type :  int64

[1 2 3 4 5]
Data Type :  int8


Convert integer to float using data type

In [13]:
import numpy as np

var1 = np.array([1, 2, 3, 4, 5], dtype= float)
print(var1)
print("Data Type : ", var1.dtype)

[1. 2. 3. 4. 5.]
Data Type :  float64


In [17]:
import numpy as np

var1 = np.array([1, 2, 3, 4, 5])
x = np.float32(var1)

print(var1)
print("Data Type : ", var1.dtype)
print()
print(x)
print("Data Type : ", x.dtype)

[1 2 3 4 5]
Data Type :  int64

[1. 2. 3. 4. 5.]
Data Type :  float32


In [18]:
## convert the data type

import numpy as np

var1 = np.array([1, 2, 3, 4, 5])
x = np.float32(var1)

new = np.int_(x)

print(var1)
print("Data Type : ", var1.dtype)
print()
print(x)
print("Data Type : ", x.dtype)
print(new)
print("Data Type : ", new.dtype)

[1 2 3 4 5]
Data Type :  int64

[1. 2. 3. 4. 5.]
Data Type :  float32
[1 2 3 4 5]
Data Type :  int64


astype() :- it can change the type of the data int to float and float to integer

In [19]:
var = np.array([1, 2, 3, 4])

x = var.astype(float)
print(var)
print(x)
print("Data type : ", x.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
Data type :  float64
