## What are arithmatic function in NumPy array 

np.min(x) :- find the minimum value in an element.

np.max(x) :- find the maximum value in an element.

np.argmin(x) :- find the minimum value at which index

np.sqrt(x) :- It calculate the square root

np.sin(x) : find the sin value

np.cos(x) : find cos value

np.cumsum(x)

How to find the mininum value in an array

In [1]:
import numpy as np
var1 = np.array([1,2,3,4,5])

x = np.array(var1)
print(np.min(x))

1


In [1]:
import numpy as np
var1 = np.array([3,4,5])
print(np.min(var1))

3


How to find the maximum value in an element

In [3]:
import numpy as np
var1 = np.array([1,2,3,4,5])

x = np.array(var1)
print(np.max(x))

5


In [ ]:
## minimum and maximum 
import numpy as np

var1 = np.array([1,2,3,4,5])
print(np.min(var1))
print(np.max(var1))

1
5


How to find the position of minimum and maximum element in an array

In [7]:
import numpy as np

var1 = np.array([1,2,3,4,5,8,9,12])
print("min : ", np.min(var1), np.argmin(var1))
print("max : ", np.max(var1), np.argmax(var1))


min :  1 0
max :  12 7


2D Array in 2D array we can find the any element using axis() parameter
axis=0 for column and axis=1 for row

In [ ]:
## axis=1 for row
import numpy as np

var1 = np.array([[1,2,3,4,],[5,1,7,2]])
print(var1)
print(np.max(var1, axis=1))


[[1 2 3 4]
 [5 6 7 2]]
[4 7]


In [15]:
## axis=1 for column
import numpy as np

var1 = np.array([[1,2,3,4,],[5,1,7,2]])
print(var1)
print(np.max(var1, axis=0))


[[1 2 3 4]
 [5 1 7 2]]
[5 2 7 4]


Calculate the square root

In [ ]:
import numpy as np

var1 = np.array([1,2,3,4])
print(var1)
print(np.sqrt(var1))


[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]


Find the sin value

In [18]:
import numpy as np

var1 = np.array([1,2,3,4])
print(np.sin(var1))


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


Find the cos value

In [20]:
import numpy as np

var1 = np.array([1,2,3,4])
print(np.cos(var1))


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


cumsum

In [23]:
var1 = np.array([1,2,3,4,5])
print(np.cumsum(var1))


[ 1  3  6 10 15]
