## Learn Shaping and Reshaping in NumPy array

Shape()

In [2]:
import numpy as np

var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print(var.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [3]:
import numpy as np

var = np.array([[1,2,3,4],[5,6,7,8]], ndmin=4)
print(var)
print(var.ndim)
print(var.shape)

[[[[1 2 3 4]
   [5 6 7 8]]]]
4
(1, 1, 2, 4)


Reshape

In [7]:
import numpy as np

var = np.array([1,2,3,4,5,6,7,8])
print(var)
x = var.reshape(4,2)
print(x)
print(var.shape)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(8,)


In [13]:
import numpy as np

var = np.array([[1,2,3,4,5,6,7,8],[8,7,6,5,4,3,2,1]])
print(var)
x = var.reshape(8,2)
print(x)
print(var.shape)
print(var.ndim)
print(x.ndim)

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [8 7]
 [6 5]
 [4 3]
 [2 1]]
(2, 8)
2
2


In [18]:
# Three dimension array

import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,1,4,5])

x = var.reshape(2,3,2)
print(x)
print(x.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 1]
  [4 5]]]
3


In [19]:
# Three dimension array

import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,1,4,5])

x = var.reshape(2,3,2)
print(x)
print(x.ndim)
print()

one = x.reshape(-1)

print(one)
print(one.ndim)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 1]
  [4 5]]]
3

[1 2 3 4 5 6 7 8 9 1 4 5]
1
