Module: NumPy Assignments

Lesson: NumPy

Assignment 1: Array Creation and Manipulation

Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

var = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(var)

# Replace all the elements in the third column with 1
var[:, 2] = 1
print("New array:")
print(var)

Original array:
[[10 10 11 19  5]
 [ 2  7 20 11  2]
 [12  2 20  1  6]
 [ 9 16 10  8 14]
 [ 1 16  2  5 19]]
New array:
[[10 10  1 19  5]
 [ 2  7  1 11  2]
 [12  2  1  1  6]
 [ 9 16  1  8 14]
 [ 1 16  1  5 19]]


Assignment 2: Array Indexing and Slicing

Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [3]:
#NumPy array of shape (6, 6) and value is 1 to 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2 . Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
#array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[12  2 17 20 20]
 [11 17 12  8  7]
 [15  1 11 18  1]
 [15 10 10 20 11]
 [ 8 15  3  5  3]]
Border elements:
[12  2 17 20 20  8 15  3  5  3 11 15 15  7  1 11]


Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1 = np.random.randint(1, 11, size=(3, 4))
arr2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 1 10  5  2]
 [ 5  8  6  9]
 [ 8  4 10  7]]
Array 2:
[[5 2 3 5]
 [5 8 7 3]
 [7 2 2 4]]
Element-wise addition:
[[ 6 12  8  7]
 [10 16 13 12]
 [15  6 12 11]]
Element-wise subtraction:
[[-4  8  2 -3]
 [ 0  0 -1  6]
 [ 1  2  8  3]]
Element-wise multiplication:
[[ 5 20 15 10]
 [25 64 42 27]
 [56  8 20 28]]
Element-wise division:
[[0.2        5.         1.66666667 0.4       ]
 [1.         1.         0.85714286 3.        ]
 [1.14285714 2.         5.         1.75      ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
arr1 = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(arr1)

# Compute the row-wise and column-wise sum
row_sum = np.sum(arr1, axis=1)
column_sum = np.sum(arr1, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


Assignment 4: Statistical Operations

Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [8]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[11 14  5  1  3]
 [15 13 15 20  3]
 [18 16 14  2 20]
 [ 3 13  9 11  1]
 [10  6 12  6 16]]
Mean: 10.28
Median: 11.0
Standard Deviation: 5.90267735862295
Variance: 34.8416


2.Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


Assignment 5: Broadcasting

Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[1 1 5]
 [3 7 6]
 [8 9 5]]
1D array:
[5 8 6]
Resulting array:
[[ 6  9 11]
 [ 8 15 12]
 [13 17 11]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 1  2  5  1]
 [ 1 10  8  3]
 [ 7  3 10  3]
 [ 5  7  3  5]]
1D array:
[8 4 4 1]
Resulting array:
[[-7 -6 -3 -7]
 [-3  6  4 -1]
 [ 3 -1  6 -1]
 [ 4  6  2  4]]


Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[10  1  4]
 [10  5  1]
 [ 8  4  9]]
Determinant: 328.0000000000001
Inverse:
[[ 0.125       0.02134146 -0.05792683]
 [-0.25        0.17682927  0.09146341]
 [ 0.         -0.09756098  0.12195122]]
Eigenvalues: [16.93626624+0.j          3.53186688+2.62538391j  3.53186688-2.62538391j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[2 8 2]
 [9 4 5]]
Array 2:
[[ 2  4]
 [10  3]
 [ 1 10]]
Matrix multiplication result:
[[86 52]
 [63 98]]


Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[14 13 14 10 15]
 [17  6  6 13 14]
 [ 2 16  1 20 20]
 [20  3 15  1  8]
 [ 8 15  8  2 17]]
Flattened array:
[14 13 14 10 15 17  6  6 13 14  2 16  1 20 20 20  3 15  1  8  8 15  8  2
 17]
Reshaped array:
[[14 13 14 10 15]
 [17  6  6 13 14]
 [ 2 16  1 20 20]
 [20  3 15  1  8]
 [ 8 15  8  2 17]]


Assignment 8: Fancy Indexing and Boolean Indexing.

Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [16]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[20  6 11  1 11]
 [ 8 13 15  2 19]
 [ 1 14  2 13 16]
 [ 2 19 11  7 12]
 [17 16 15 11 14]]
Corner elements:
[20 11 17 14]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [17]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[ 5 12  2  3]
 [ 3  8  3  6]
 [10 17 13 15]
 [20 15 10 19]]
Modified array:
[[ 5 10  2  3]
 [ 3  8  3  6]
 [10 10 10 10]
 [10 10 10 10]]


Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [18]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [19]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [20]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 8  1  8  6]
 [ 6 18  8 16]
 [19 10  1  9]
 [10 19  2  9]]
Masked array:
[[8 1 8 6]
 [6 -- 8 --]
 [-- 10 1 9]
 [10 -- 2 9]]
Sum of unmasked elements: 78


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [21]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[16  5  6]
 [ 4 17  5]
 [17 11 11]]
Masked array:
[[-- 5 6]
 [4 -- 5]
 [17 11 --]]
Modified masked array:
[[ 8  5  6]
 [ 4  8  5]
 [17 11  8]]
